// <auto-generated />
using System;
using Api.AudioExtractions.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace api.AudioExtractions.Persistence.Migrations
{
    [DbContext(typeof(AudioExtractionDbContext))]
    [Migration("20261002174450_InitialAudioExtractions")]
    partial class InitialAudioExtractions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.AudioExtractions.Persistence.Entities.AudioExtractionRequestEntity", b =>
                {
                    b.Property<string>("RequestId")
                        .HasMaxLength(43)
                        .HasColumnType("character varying(43)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EndSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("IdempotencyKeyHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("IdempotencyRequestHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("OutputFormat")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("ResultChecksumSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("ResultDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("ResultObjectKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<long?>("ResultSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("SourceDurationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("StartSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.HasKey("RequestId");

                    b.HasIndex("IdempotencyKeyHash")
                        .IsUnique()
                        .HasDatabaseName("IX_audio_extraction_requests_idempotency_key_hash");

                    b.ToTable("audio_extraction_requests", null, t =>
                        {
                            t.HasCheckConstraint("CK_audio_extraction_requests_idempotency_hashes", "(\"IdempotencyKeyHash\" IS NULL) = (\"IdempotencyRequestHash\" IS NULL)");

                            t.HasCheckConstraint("CK_audio_extraction_requests_interval", "\"StartSeconds\" >= 0 AND \"EndSeconds\" > \"StartSeconds\"");

                            t.HasCheckConstraint("CK_audio_extraction_requests_interval_limit", "\"EndSeconds\" - \"StartSeconds\" <= 1800 AND \"EndSeconds\" <= \"SourceDurationSeconds\"");

                            t.HasCheckConstraint("CK_audio_extraction_requests_output_format", "\"OutputFormat\" = 'mp3'");

                            t.HasCheckConstraint("CK_audio_extraction_requests_source_duration", "\"SourceDurationSeconds\" > 0 AND \"SourceDurationSeconds\" <= 21600");

                            t.HasCheckConstraint("CK_audio_extraction_requests_status", "\"Status\" IN ('accepted', 'completed', 'failed')");

                            t.HasCheckConstraint("CK_audio_extraction_requests_terminal_fields", "(\"Status\" = 'accepted' AND \"ExpiresAt\" IS NULL AND \"ResultObjectKey\" IS NULL AND \"ResultSizeBytes\" IS NULL AND \"ResultChecksumSha256\" IS NULL AND \"ResultDurationSeconds\" IS NULL AND \"FailureCode\" IS NULL AND \"FailureMessage\" IS NULL) OR (\"Status\" = 'completed' AND \"ExpiresAt\" IS NOT NULL AND \"ResultObjectKey\" IS NOT NULL AND \"ResultSizeBytes\" BETWEEN 1 AND 104857600 AND LENGTH(\"ResultChecksumSha256\") = 64 AND \"ResultDurationSeconds\" > 0 AND ABS(\"ResultDurationSeconds\" - (\"EndSeconds\" - \"StartSeconds\")) <= 2 AND \"FailureCode\" IS NULL AND \"FailureMessage\" IS NULL) OR (\"Status\" = 'failed' AND \"ExpiresAt\" IS NOT NULL AND \"FailureCode\" IS NOT NULL AND \"FailureMessage\" IS NOT NULL AND \"ResultObjectKey\" IS NULL AND \"ResultSizeBytes\" IS NULL AND \"ResultChecksumSha256\" IS NULL AND \"ResultDurationSeconds\" IS NULL)");
                        });
                });

            modelBuilder.Entity("Api.AudioExtractions.Persistence.Entities.NotificationOutcomeEntity", b =>
                {
                    b.Property<string>("RequestId")
                        .HasMaxLength(43)
                        .HasColumnType("character varying(43)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("SafeMessage")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("RequestId");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("audio_extraction_notification_outcomes", null, t =>
                        {
                            t.HasCheckConstraint("CK_audio_extraction_notification_status", "\"Status\" IN ('completed', 'failed')");
                        });
                });

            modelBuilder.Entity("Api.AudioExtractions.Persistence.Entities.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("character varying(43)");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("EventId");

                    b.HasIndex("RequestId");

                    b.HasIndex("State", "NextAttemptAt")
                        .HasDatabaseName("IX_audio_extraction_outbox_state_next_attempt");

                    b.ToTable("audio_extraction_outbox", null, t =>
                        {
                            t.HasCheckConstraint("CK_audio_extraction_outbox_attempt_count", "\"AttemptCount\" >= 0");

                            t.HasCheckConstraint("CK_audio_extraction_outbox_published_at", "(\"State\" = 'published' AND \"PublishedAt\" IS NOT NULL) OR (\"State\" = 'pending' AND \"PublishedAt\" IS NULL)");

                            t.HasCheckConstraint("CK_audio_extraction_outbox_state", "\"State\" IN ('pending', 'published')");
                        });
                });

            modelBuilder.Entity("Api.AudioExtractions.Persistence.Entities.ProcessedEventEntity", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EventId");

                    b.ToTable("audio_extraction_processed_events", (string)null);
                });

            modelBuilder.Entity("Api.AudioExtractions.Persistence.Entities.NotificationOutcomeEntity", b =>
                {
                    b.HasOne("Api.AudioExtractions.Persistence.Entities.AudioExtractionRequestEntity", "Request")
                        .WithOne("NotificationOutcome")
                        .HasForeignKey("Api.AudioExtractions.Persistence.Entities.NotificationOutcomeEntity", "RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Api.AudioExtractions.Persistence.Entities.OutboxMessageEntity", b =>
                {
                    b.HasOne("Api.AudioExtractions.Persistence.Entities.AudioExtractionRequestEntity", "Request")
                        .WithMany("OutboxMessages")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Api.AudioExtractions.Persistence.Entities.AudioExtractionRequestEntity", b =>
                {
                    b.Navigation("NotificationOutcome");

                    b.Navigation("OutboxMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
